[tool.poetry]
name = "pythonisms"
version = "0.1.0"
description = ""
authors = ["Noura-Alquran <nmalquran15@eng.just.edu.jo>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
